#------ Config ------#
Saves path: C:\Users\ryan\AppData\Roaming\.minecraft\saves # Path to local minecraft saves directory
World: topomc15    # Name of world to map
PDF save location: ./examples/debug.pdf    # Leave this blank to avoid saving to anywhere

#------ Map ------#
Scale: 1:1000    # Scale of map for PDF output

#------ Preview ------#
Preview size: 1    # Size of preview window

#------ Contours ------#
Interval: 1    # Height distance between drawn contours
Phase: 0    # What height the first contour is drawn at
Index: 5    # The amount of standard contours for each index contour. Set to 0 to turn off
Smoothness: 1    # Intensity of Gaussian1D smoothing level (sigma). Set to 0 to turn off
Line width: 1

#------ Blocks ------#
Surface blocks:    # Blocks considered 'ground level'
  - grass_block
  - grass_path
  - dirt
  - coarse_dirt
  - farmland

  - sand
  - sandstone

  - red_sand
  - red_sandstone

  - clay

  - podzol
  - mycelium

  - stone
  - granite
  - diorite
  - andesite
  - gravel

  - coal_ore
  - iron_ore
  - gold_ore

  - water
